### ISSUE TITLE
Age Command

### ISSUE THREAD

**Issue by MoWobbler** [C4K3/Misc#6]
The age command no longer works for 1.16, here's the error message: 
[Misc] Plugin Misc v4 has failed to register events for class main.java.net.simpvp.Misc.AgeCommand because org/kitteh/vanish/event/VanishStatusChangeEvent does not exist.

**Comment by C4K3** [comment]
Does it work if you install VanishNoPacket on the server?

**Comment by MoWobbler** [comment]
That is most likely the problem, I'll try it out. Thanks
